version: '3.3'

services:
 
  db:
    image: mysql:latest
    container_name: mysql-db2
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    restart: always
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - "8082:80"
    restart: always

    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

  accountancy:
    image: accountancy
    container_name: accountancy-app
    build:
      context: ./AccountancyApp
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/accountancy?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    restart: always
  
  transaction-maker:
    image: transaction-maker
    container_name: transaction-maker
    build:
      context: ./TransactionMaker
      dockerfile: Dockerfile
    depends_on:
      - accountancy
    environment:
      USER_SAVE_URI: http://accountancy-app:8080/user/save
      ACCOUNT_SAVE_URI: http://accountancy-app:8080/account/save
      TRANSACTION_SAVE_URI: http://accountancy-app:8080/transaction/save
    ports:
      - "8090:8090"
    restart: always

